name: $(Date:yyyyMMdd)

pool:
  name: Ubuntu20
  
resources:
  repositories: 
    - repository: product-terraform
      type: git
      name: 'ISM/ism-azure-terraform'
    - repository: terraform-modules
      type: git
      name: 'DevOps/terraform-modules'
    - repository: tfm-k8s
      type: git
      name: TFM/terraform-provisioner-k8s
      ref: refs/tags/ism


trigger:
  - none
  
stages:
  - template: /pipeline_templates/terraform_apply.yml@terraform-modules
    parameters:
        cloud: "azure"
        variableGroup: "ism-esm-aks-infra"
        tfstack_path: "ism-azure-terraform/ism"
        tfstate_resource_group: 'esmcw-terraform-states'
        tfstate_storage_account: 'esmcwterraformstates'
        tfstate_container: 'esmcw-terraform-states'
        tfstate_key: "nvw-try"
        tfvars_name: "nvw-try"
        tf_command_extra_params: >-
          -var="servicePrincipalId=$(servicePrincipalId)"
          -var="servicePrincipalKey=$(servicePrincipalKey)"
          -var=acrPullSecret=$(AcrPullSecret)"
        service_connection_plan: "azure-terraform-cherwell-plan"
        service_connection_apply: "azure-terraform-cherwell-apply"
        service_connection_security: "azure-terraform-cherwell-apply"