name: $(Date:yyyyMMdd)

pool:
  name: Ubuntu20
  
resources:
  repositories: 
    - repository: product-terraform
      type: git
      name: 'ISM/ism-azure-terraform'
    - repository: terraform-modules
      type: git
      name: 'DevOps/terraform-modules'

trigger:
  - none

stages:
  - stage: "Plan_global"
    dependsOn: []
    jobs: 
      - template: /pipeline_templates/terraform_jobs_azure.yml@terraform-modules
        parameters:
          tf_command: "plan"
          tfstack_name: "common_stack"
          tfstack_path: "ism-azure-terraform/global"
          tfstate_resource_group: 'esm-terraform-states'
          tfstate_storage_account: 'esmterraformstates'
          tfstate_container: 'esm-terraform-states'   
          tfstate_key: "global"
          tfvars_name: "ivantiesm"
          service_connection: "azure-terraform-esm-plan"
  - stage: "Apply_global"
    dependsOn: "Plan_global"
    jobs: 
      - template: /pipeline_templates/terraform_jobs_azure.yml@terraform-modules
        parameters:
          tf_command: "apply"
          tfstack_name: "common_stack"
          tfstack_path: "ism-azure-terraform/global"
          tfstate_resource_group: 'esm-terraform-states'
          tfstate_storage_account: 'esmterraformstates'
          tfstate_container: 'esm-terraform-states'             
          tfstate_key: "global"
          tfvars_name: "ivantiesm"
          service_connection: "azure-terraform-esm-apply"
