name: $(Date:yyyyMMdd)

pool:
  name: Ubuntu20
  
resources:
  repositories: 
    - repository: product-terraform
      type: git
      name: 'ISM/ism-aws-terraform'
    - repository: terraform-modules
      type: git
      name: 'DevOps/terraform-modules'

trigger:
  - none
  
stages:
  - template: /pipeline_templates/terraform_apply_st_app_sec.yml@terraform-modules
    parameters:
        cloud: "aws"    
        tfstack_path: "ism-aws-terraform/prd"
        tfstate_bucket: "ivanti-fedramp-terraform-states"
        tfstate_key: "ism/prd-nvf"
        tfvars_name: "prd-nvf"
        service_connection_plan: "aws-terraform-fedramp-plan"
        service_connection_apply: "aws-terraform-fedramp-apply"
        service_connection_security: "aws-terraform-fedramp-security"
  